# Generated by Django 4.0.4 on 2022-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('caregiver_mail', models.TextField()),
            ],
            options={
                'db_table': 'Elderly',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(db_column='interest_ID', default=-1, primary_key=True, serialize=False)),
                ('interest_name', models.TextField()),
            ],
            options={
                'db_table': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('condition_id', models.AutoField(db_column='condition_ID', default=-1, primary_key=True, serialize=False)),
                ('condition_name', models.TextField()),
            ],
            options={
                'db_table': 'Medical_Condition',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(db_column='request_ID', default=-1, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('time', models.TextField()),
                ('category', models.TextField()),
                ('requester', models.IntegerField()),
                ('volunteer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField()),
                ('id', models.AutoField(db_column='ID', default=-1, primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('bio', models.TextField()),
                ('photograph', models.ImageField(upload_to='user_dp')),
                ('age', models.IntegerField()),
                ('mail', models.TextField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(db_column='ID', default=-1, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('score', models.IntegerField()),
                ('occupation', models.TextField()),
            ],
            options={
                'db_table': 'Volunteer',
            },
        ),
        migrations.CreateModel(
            name='VolunteerReview',
            fields=[
                ('surrogate_key', models.AutoField(db_column='ignore', default=-1, primary_key=True, serialize=False)),
                ('volunteer_id', models.IntegerField(db_column='volunteer_ID')),
                ('elderly_id', models.IntegerField(db_column='elderly_ID')),
                ('review_contents', models.TextField(blank=True, null=True)),
                ('star_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Volunteer_Review',
                'unique_together': {('volunteer_id', 'elderly_id')},
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('surrogate_key', models.AutoField(db_column='ignore', default=-1, primary_key=True, serialize=False)),
                ('friend1', models.IntegerField(db_column='Friend1')),
                ('friend2', models.IntegerField(db_column='Friend2')),
            ],
            options={
                'db_table': 'Friend',
                'unique_together': {('friend1', 'friend2')},
            },
        ),
        migrations.CreateModel(
            name='Elderlyxinterest',
            fields=[
                ('surrogate_key', models.AutoField(db_column='ignore', default=-1, primary_key=True, serialize=False)),
                ('elderly_id', models.IntegerField(db_column='elderly_ID')),
                ('interest_id', models.IntegerField(db_column='interest_ID')),
            ],
            options={
                'db_table': 'ElderlyXInterest',
                'unique_together': {('elderly_id', 'interest_id')},
            },
        ),
        migrations.CreateModel(
            name='Elderlyxcondition',
            fields=[
                ('surrogate_key', models.IntegerField(db_column='ignorable', default=-1, primary_key=True, serialize=False)),
                ('elderly_id', models.IntegerField(db_column='elderly_ID')),
                ('condition_id', models.IntegerField(db_column='condition_ID')),
            ],
            options={
                'db_table': 'ElderlyXCondition',
                'unique_together': {('elderly_id', 'condition_id')},
            },
        ),
    ]
