# Generated by Django 4.0.4 on 2022-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeaConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.AutoField(db_column='request_ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='photograph',
            field=models.TextField(),
        ),
    ]
