# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeaConnect', '0002_alter_request_request_id_alter_user_photograph'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volunteerreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='volunteerreview',
            name='surrogate_key',
            field=models.AutoField(db_column='ignore', primary_key=True, serialize=False),
        ),
    ]
